package nebrija.gestionVideojuegos.modelo;

public enum CompaniaEnum { //FUNCIONAL EN CASO DE NO EXISTENCIA DE BD
    SEGA, ANNAPURNA_INTERACTIVE, CAPCOM, SONY, ACTIVISION_BLIZZARD, MICROSOFT, AKSYS_GAMES, NO_MORE_ROBOTS, NINTENDO, DEVOLVER_DIGITAL, SQUARE_ENIX, XSEED, UBISOFT, FOCUS_HOME_INTERACTIVE, BETHESDA_SOFTWORKS, TEAM17
}
